http://localhost:3001/api/persons
###
DELETE http://localhost:3001/api/persons/5e8317bbe190bc2a1777ecbd
###
http://localhost:3001/api/persons/5e8317bbe190bc2a1777ecbd
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "weweq",
    "number": "31231312"
}
###
http://localhost:3001/info
###
https://glacial-coast-95448.herokuapp.com/api/persons
###
https://glacial-coast-95448.herokuapp.com/info